### ISSUE TITLE
object-detection.pbtxt can not be found.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [Dharun/TensorPy#4]
Do i have to train the model again to obtain object-detection.pbtxt? This error occured when i run numberplate_recognition_detection.py:
```
Traceback (most recent call last):
  File "C:\Users\DELL\Downloads\Tensorflow-License-Plate-Detection-master\Tensorflow-License-Plate-Detection-master\numplate_recognition_detection.py", line 34, in <module>
    label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
  File "C:\Users\DELL\Downloads\Tensorflow-License-Plate-Detection-master\Tensorflow-License-Plate-Detection-master\object_detection\utils\label_map_util.py", line 117, in load_labelmap
    label_map_string = fid.read()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 120, in read
    self._preread_check()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: training\object-detection.pbtxt : The system cannot find the path specified.

; No such process
```

**Comment by Dharun** [comment]
item {
id: 1
name: 'numplate'
}
Save the above code as **object-detection.pbtxt**

**Comment by FrancescoManigrass** [comment]
where i have to save this file ? thank you

**Comment by Sreerag-ibtl** [comment]
I have not tried the code. But the path is given as training/object-detection.pbtxt in numplate_recognition_detection.py. That means the file should be inside the directory 'training', which has to be in the current working directory.
