### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 12: invalid start byte

### ISSUE THREAD

**Issue by hongq123** [Dharun/TensorPy#5]
Traceback (most recent call last):
  File "numplate_recognition_detection.py", line 81, in <module>
    text = pytesseract.image_to_string(Image.open(filename),lang=None)
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\pytesseract\pytesseract.py", line 294, in image_to_string
    return run_and_get_output(*args)
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\pytesseract\pytesseract.py", line 202, in run_and_get_output
    run_tesseract(**kwargs)
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\pytesseract\pytesseract.py", line 178, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
  File "D:\Anaconda3\envs\tensorflow_gpu\lib\site-packages\pytesseract\pytesseract.py", line 79, in get_errors
    line for line in error_string.decode('utf-8').splitlines()

Excuse me！ I meet this problem when I run the code. Do you know how to solve it?

**Comment by Dharun** [comment]
@hongq123 I guess you haven't installed **pytesseract** & **Tesseract engine**.

**Comment by Dharun** [comment]
pip install pytesseract
